version: '3'
services:
  prometheus:
    image: "prom/prometheus"
    ports:
     - "19090:9090"
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: acutaor-prometheus
  grafana:
     image: "grafana/grafana"
     ports:
     - "13000:3000"
     container_name: acutaor-grafana
