version: '2.1'

services:
    limit-service:
      build: .
      ports:
       - "8080:8080"
      depends_on:
       - mysql
        
    mysql:
      image: mysql
      ports:
       - "3306:3306"
      environment:
        MYSQL_DATABASE: test
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_HOST: 'localhost'
        DATABASE_USER: root