/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Student;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-12-05T13:59:30.300Z")

@Api(value = "student", description = "the student API")
public interface StudentApi {

    @ApiOperation(value = "summary", nickname = "studentGet", notes = "desc", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK") })
    @RequestMapping(value = "/student",
        method = RequestMethod.GET)
    List<Student> studentGet();


    @ApiOperation(value = "summary", nickname = "studentPost", notes = "desc", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK") })
    @RequestMapping(value = "/student",
        method = RequestMethod.POST)
    ResponseEntity<Void> studentPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Student body);

}
