spring:
       jpa:
          properties:
                hibernate:
                     ddl-auto:update
                     format_sql:true
          generate-ddl: true
          
          show-sql: true

       datasource:
          platform: mysql
          driver-class-name:  com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/restdb?useSSL=false
          username: root
          password: root
   